py_test(
    name = "server_config_setup_test",
    srcs = ["server_config_setup_test.py"],
    data = [
        "//:th_transformer_config",
    ],
    deps = [
        "//rtp_llm/models_py/standalone:py_standalone_testlib",
    ],
)
